services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: bitnami/postgresql:latest
    container_name: postgres_bitnami
    restart: always
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: fatechub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: